name: DiabeticRetinopathyEnv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11

  # Scientifiche
  - numpy
  - pandas
  - scikit-learn

  # Immagini e visualizzazione
  - opencv
  - matplotlib
  - pillow
  - tqdm

  # PyTorch con GPU (CUDA 12.1)
  - pytorch=2.3
  - torchvision=0.18
  - pytorch-cuda=12.1

  # Altre utilit√†
  - pip
  - pip:
      - torchinfo
      - focal-loss-torch
